CC = arch -x86_64 cc
CFLAGS = -Wall -Wextra -Werror
OPTION = -L./mlx -lmlx -framework Metal -framework Metalkit
INCLUDES = -I./include
SRCS = $(addprefix ./src/, ${SRCS_FILES})

SRCS_FILES = main.c \

OBJS = $(SRCS:.c=.o)
NAME = cub3d

all : $(NAME)

$(NAME) : $(OBJS)
	$(CC) $(OPTION) $(CFLAGS) $(INCLUDES) -o $@ $^

%.o : %.c
	$(CC) $(CFLAGS) -c -o $@ $^ $(INCLUDES)

clean :
	rm -rf $(OBJS)

fclean : clean
	rm -rf $(NAME)

re :
	make fclean
	make all

.PHONY : all bonus clean fclean re